name: Build & Release

on: 
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: "21"

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - run: gradle nativeCompile

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: "mmsim-${{matrix.os}}"
        path: "build/native/nativeCompile"

  release:
    runs-on: ubuntu-latest

    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    permissions:
      contents: write

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - run: |
        # set permissions for unix style OS
        chmod +x ./mmsim-{macos,ubuntu}-latest/mmsim
        # rename for release
        mkdir release
        zip release/mmsim-x86_64-darwin.zip  mmsim-macos-latest/mmsim
        zip release/mmsim-x86_64-linux.zip   mmsim-ubuntu-latest/mmsim
        zip release/mmsim-x86_64-windows.zip mmsim-windows-latest/mmsim.exe

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          release/*
